### ISSUE TITLE
Are you mad?

### ISSUE THREAD

**Issue by Edwardchengar** [houshanren/hangzhou_house_knowledge#100]
So you just use the opensource software development platform as a forum and shares non-tech stuff here?
I don't think it is proper way to share the knowledge of the morbid property market in here. Please close the project

**Comment by houshanren** [comment]
@Edwardchengar  我只是觉得大家买房不容易，让大家买房的时候能少走点弯路，另外里面都是很多高清图片，大家可以随时fork 或者下载。如果说确实我这么做不妥肯定会关闭掉。

**Comment by Edwardchengar** [comment]
so you think everybody in github are suffer from property market in China?It is quite meaningless to people who are not living in China or don't know Chinese. Actually you can go to something like "Badu" or "tianya" (forum in China?). Please don't abuse or even contaminate the platform.

**Comment by Bernido** [comment]
Hi @Edwardchengar,
I wish you could understand the difficulties of building a private web site in mainland China as a Chinese citizen. Personal web sites are strictly forbidden in China by the GOV. To use github with this topic is some kind of walk around. Hope you would see this.
Best wishes.

**Comment by aforwardz** [comment]
@Edwardchengar 看得懂就用中文回复谢谢

**Comment by Bernido** [comment]
@aforwardz 也许用的是translate.google.com
白天不懂夜的黑

**Comment by aforwardz** [comment]
@Bernido ok，he's at HK

**Comment by houshanren** [comment]
@Edwardchengar  我已经开通了gitbook ， https://houshanren.gitbooks.io/hangzhou_house_knowledge/content/ 后续会让价移步到gitbook

**Comment by Edwardchengar** [comment]
why I need to use chinese in an international platform?( ys I know how to read but I don't know how to type it so please feel free to use chinese to discuss with me but I won't and I can't type chinese)
I am saying the proper use of the platform and it is a little bit non sense if you are saying the difficulties of building private website in China. You can post it in tweet or Facebook but why github? I can't see any point of sharing how to buy an expensive house is related to software development or even STEM

**Comment by Edwardchengar** [comment]
Ya. That's great if you just shifted it to gitbook. Thank you

**Comment by flandycheng** [comment]
@Edwardchengar 
1. We are not suffering from the property market in China, we take it as a common issue of daily life of us and economic development of China. So please take back your word "suffer".
2. Github is an opensource software development platform for sharing, but not only tech stuff are restricted here.  Everything related to programmers could be shared , that's part of our life, we enjoy and encourage the work&life everywhere, including The Github! So please wash away your "tech-only" thought.

**Comment by Bernido** [comment]
If you do not like the site here, you just unsubscribe this thread. Then you will not mad on stuff here.
Per the information of the time line, if you are really a Hongkonger, I guess you suffer more from real estate problem in HK.

**Comment by moscartong** [comment]
I agree with @Edwardchengar . Github is a place for softward projects and ideas, not a forum. Also it's an international site here, we should consider users from all languages so using a common language like English should be required.

I understand how difficult it is to publish content online in mainland China. I myself live in mainland China. I suffer internet censorship every fucking minute. I have to use VPN all time in order to have a normal online life. But that's no excuse for sharing this on Github. There are certainly other places more appropriate for contents like this.

**Comment by lln7777** [comment]
发现一个假洋鬼子，不喜欢就别来。不喜欢中国就不要操心中国的事情，中国的事情你也不懂。
如果你故意看不懂，OK. I Speak English. You can, You up, No can, No BB.
