### ISSUE TITLE
似乎大家都很想看到：国人被 Github 屏蔽，国内程序员不受外界待见

### ISSUE THREAD

**Issue by hidetag** [houshanren/hangzhou_house_knowledge#131]
Github 是国际化的，单纯的技术分享社区，不是国内乌烟瘴气的贴吧，什么乱七八糟的东西都往这里面丢，着实丢国人的脸。
这项目有心血，但是不该丢到这里面来，你放你自己的博客就是了，放到这来做什么。。分享给全世界看么，有什么用。。
希望 Github 不要被国人搞砸了，多好的一个平台，偏要像贴吧一样乌烟瘴气么？
Issue 里一堆什么招聘信息。。

**Comment by houshanren** [comment]
@hidetag  本来是给朋友弄的，里面有些高清图大家我朋友也是程序员用起来比较方便。加星没想过，我正在弄gitbook 弄完了关闭此项目。给您造成的不便深表歉意。

**Comment by lln7777** [comment]
有一个道德大师

**Comment by yifeikong** [comment]
站在道德制高点你不冷么

**Comment by fcyu** [comment]
这跟道德有什么关系？本来楼主就不在道德高点好吗。

GitHub没有规定只能用来放程序代码。而且，GitHub也鼓励建立个人博客啊。

楼主这种不了解条款就乱喷，才是对GitHub最大的不尊敬吧。

**Comment by moscartong** [comment]
老实说，我是挺希望Github被墙的，这样少了很多只会谩骂的用户能上来这里，我对道德啥的没啥意见，但我赞同国内的网站真是乌烟瘴气，包括很多技术社区，乱七八糟。

**Comment by hidetag** [comment]
@lln7777 哈哈哈，道德大师？我为你感到悲哀。一个二个道德制高点，你们自己多高尚？发个 0 code 的项目到崇尚 code 的社区，很自豪么？要不你们发点，多发点，跑脚本点星如何？不知道有 Gitbooks 么？不知道有 Github Pages 么？整天道德道德挂在嘴边，你们累么？有什么问题直接拿道德说事，我只能说你`MMP`高尚的一批。

**Comment by hidetag** [comment]
@yifeikong 冷，特别冷，非常冷，可我不是道德婊，不像有些人，道德二字随时挂嘴边。

**Comment by hidetag** [comment]
@fcyu 注意你的措辞，鼓励建立个人博客，是简历个人博客，那么这种东西完全可以放到 GitHub Pages 去，为何不呢？确实没有规定只能放代码，但放代码是共识。没规定只能放代码，我在上面卖东西，发广告，招聘也可以了？

**Comment by fcyu** [comment]
@hidetag 我觉得我的措辞没有不妥。请问，我说的那几句话里面哪句话不是事实?

“这种东西”当然可以放到GitHub Pages去，当然也可以放到这里，为何不可呢？

你哪里查到了放代码是共识？退一万步讲，就算是共识，也不是不允许放其他内容，更可况已经有很多先例。

你可以在上面卖东西，发广告啊，前提是要有人看。没人看你发了不就白发，自己亏本么？相反，这个repo很多人看，很受欢迎，不是一个成功的例子吗?

最后，请注意你的行为。口口声声把GitHub精神说的这么高尚，却在没有解决issue，没有征求任何人的情况下擅自关闭issue。这时候你的“清高”哪里去了?

**Comment by hidetag** [comment]
@fcyu 我说的就不是事实了？我问你比特币能够进行支付，这个是共识么？
用你的话说，这是我的 issue，我能关闭它，不存在擅自不擅自，毕竟我在 Github 发什么都无所谓，即使是广告，售卖；全篇道德制高点，你觉得还有必要这么交流下去么？

**Comment by fcyu** [comment]
@hidetag 请问，你在哪里看到“GitHub放代码是共识？”请引用。

这是你的issue，但是开issue就是为了大家共同讨论，解决为题。你容不得别人回复，就把issue关了，你的“清高”允许你这么做吗?
