### ISSUE TITLE
作为一个有时候没事会翻翻排行榜的人来说这个项目真的惹怒我了，已向github提出举报

### ISSUE THREAD

**Issue by a358003542** [houshanren/hangzhou_house_knowledge#148]
This project has a little relation with the code at all  but just how to buy a house in china city of hangzhou. 
Frankly speaking  This project has a advertising property， and in the issue there are many recruit information, wikepedia has the good  fame of no advertising policy , I hope the GitHub project still have your bottom line : 

 GitHub is how people build software

**Comment by Allianzcortex** [comment]
Sincerely this project really has no relation with the code，But it  doesn't contradict with the principle of github.

**Comment by Allianzcortex** [comment]
@358003542 You have the Right to report to the github，and the maintainer Certainly has the right to publish new commits.Just let the authority judge which one is righ.

**Comment by shrekboss** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lingkai1** [comment]
***@***.***已成功抓取您发送的数据包！

**Comment by Anankeg** [comment]
邮件已收到，会尽快回复
